//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mastermind.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mastermind.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Abandonnées.
        /// </summary>
        public static string Abandoned {
            get {
                return ResourceManager.GetString("Abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tentatives.
        /// </summary>
        public static string Attempts {
            get {
                return ResourceManager.GetString("Attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moyenne de coups.
        /// </summary>
        public static string AverageScore {
            get {
                return ResourceManager.GetString("AverageScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moins de coups.
        /// </summary>
        public static string BestScore {
            get {
                return ResourceManager.GetString("BestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez vos couleurs.
        /// </summary>
        public static string ChooseColors {
            get {
                return ResourceManager.GetString("ChooseColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couleurs.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez perdu :-(.
        /// </summary>
        public static string ComputerWin {
            get {
                return ResourceManager.GetString("ComputerWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configurations.
        /// </summary>
        public static string Configurations {
            get {
                return ResourceManager.GetString("Configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer vos choix.
        /// </summary>
        public static string ConfirmChoices {
            get {
                return ResourceManager.GetString("ConfirmChoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmer le mot de passe.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si la combinaison est correcte.
        /// </summary>
        public static string CorrectCombinationTitle {
            get {
                return ResourceManager.GetString("CorrectCombinationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configurations actuelles.
        /// </summary>
        public static string CurrentConfigurations {
            get {
                return ResourceManager.GetString("CurrentConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tableau de bord.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier le profil.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Courriel.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le courriel est requis.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom complet.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom complet est requis.
        /// </summary>
        public static string FullNameRequired {
            get {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parties abandonnées.
        /// </summary>
        public static string GamesAbandoned {
            get {
                return ResourceManager.GetString("GamesAbandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parties perdues.
        /// </summary>
        public static string GamesLost {
            get {
                return ResourceManager.GetString("GamesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sommaire de toutes les parties.
        /// </summary>
        public static string GameSummary {
            get {
                return ResourceManager.GetString("GameSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parties gagnées.
        /// </summary>
        public static string GamesWon {
            get {
                return ResourceManager.GetString("GamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configurations globales.
        /// </summary>
        public static string GlobalConfigurations {
            get {
                return ResourceManager.GetString("GlobalConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le but de Mastermind.
        /// </summary>
        public static string HomeGoalTitle {
            get {
                return ResourceManager.GetString("HomeGoalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commencer une partie de Mastermind.
        /// </summary>
        public static string HomeStartTitle {
            get {
                return ResourceManager.GetString("HomeStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bienvenue.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si la combinaison présentée est incorrecte.
        /// </summary>
        public static string IncorrectCombinationTitle {
            get {
                return ResourceManager.GetString("IncorrectCombinationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur ou mot de passe invalide..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déconnexion.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Perdues.
        /// </summary>
        public static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez droit à {0} propositions pour déchiffrer le code..
        /// </summary>
        public static string MastermindAttemptsText {
            get {
                return ResourceManager.GetString("MastermindAttemptsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous continuez ainsi en proposant sur la seconde ligne une autre proposition, en prenant bien entendu en compte les marqueurs noirs et blancs. Vous avez droit à {0} propositions pour déchiffrer le code, sinon vous serez déclaré perdant et la combinaison secrète sera révélée. Vous pourrez ainsi analyser votre partie si vous le désirez..
        /// </summary>
        public static string MastermindContinueText {
            get {
                return ResourceManager.GetString("MastermindContinueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez réussi le défi et la combinaison secrète sera révélée..
        /// </summary>
        public static string MastermindCorrectText {
            get {
                return ResourceManager.GetString("MastermindCorrectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le but du Mastermind est de trouver la combinaison secrète composée de {0} couleurs dans un maximum de {1} coups..
        /// </summary>
        public static string MastermindGoalText {
            get {
                return ResourceManager.GetString("MastermindGoalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les marqueurs noirs représentent les bonnes couleurs bien placées et les blancs les bonnes couleurs mal placées..
        /// </summary>
        public static string MastermindIncorrectText {
            get {
                return ResourceManager.GetString("MastermindIncorrectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si dans la proposition, un ou plusieurs pions de couleurs sont bien dans la combinaison mais pas à la bonne place, des marqueurs blancs seront positionnés selon le nombre dans la partie de droite de la ligne. Si dans la proposition, un ou plusieurs pions de couleurs sont bien dans la combinaison et à la bonne place, ce sont des marqueurs noirs qui seront utilisés. Prendre note que la position des marqueurs n&apos;est pas liée à la position de la proposition. Les marqueurs noirs sont d&apos;abord affichés, ensuite les [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string MastermindMarkersText {
            get {
                return ResourceManager.GetString("MastermindMarkersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez simplement positionner {0} pions dans la première ligne située complètement en bas..
        /// </summary>
        public static string MastermindPlacementText {
            get {
                return ResourceManager.GetString("MastermindPlacementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pour commencer, il vous suffit de sélectionner &quot;Jouer une partie&quot; en cliquant sur le bouton ci-bas ou via le menu principal..
        /// </summary>
        public static string MastermindStartText {
            get {
                return ResourceManager.GetString("MastermindStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comparez vos meilleures lignes pour éliminer certaines couleurs et positions..
        /// </summary>
        public static string MastermindTipsText {
            get {
                return ResourceManager.GetString("MastermindTipsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez choisir entre {1} et {2} tentatives..
        /// </summary>
        public static string NbAttemptsRange {
            get {
                return ResourceManager.GetString("NbAttemptsRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de couleurs.
        /// </summary>
        public static string NbColors {
            get {
                return ResourceManager.GetString("NbColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez choisir entre {1} et {2} couleurs..
        /// </summary>
        public static string NbColorsRange {
            get {
                return ResourceManager.GetString("NbColorsRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de positions.
        /// </summary>
        public static string NbPositions {
            get {
                return ResourceManager.GetString("NbPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez choisir entre {1} et {2} positions..
        /// </summary>
        public static string NbPositionsRange {
            get {
                return ResourceManager.GetString("NbPositionsRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de tentatives.
        /// </summary>
        public static string NbTries {
            get {
                return ResourceManager.GetString("NbTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle partie.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le mot de passe est requis..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez gagné !.
        /// </summary>
        public static string PlayerWin {
            get {
                return ResourceManager.GetString("PlayerWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jouer une partie.
        /// </summary>
        public static string PlayGame {
            get {
                return ResourceManager.GetString("PlayGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Positions.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantité.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Règlements inspirés de.
        /// </summary>
        public static string RegulationsInspired {
            get {
                return ResourceManager.GetString("RegulationsInspired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejouer.
        /// </summary>
        public static string Replay {
            get {
                return ResourceManager.GetString("Replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Résultat.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Règlements.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Partie en cours....
        /// </summary>
        public static string RunningGame {
            get {
                return ResourceManager.GetString("RunningGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inscription.
        /// </summary>
        public static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vos statistiques.
        /// </summary>
        public static string StatsTitle {
            get {
                return ResourceManager.GetString("StatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Astuces pour déchiffrer la combinaison secrète du Mastermind.
        /// </summary>
        public static string TipsTitle {
            get {
                return ResourceManager.GetString("TipsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nom d&apos;utilisateur est requis..
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur déjà pris..
        /// </summary>
        public static string UsernameTaken {
            get {
                return ResourceManager.GetString("UsernameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Site Web.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gagnées.
        /// </summary>
        public static string Won {
            get {
                return ResourceManager.GetString("Won", resourceCulture);
            }
        }
    }
}
